Item = input("Name An Item: ")
Color = input("Pick A Color: ")
Emotion = input("Pick An Emotion: ")
Emotion2 = input("Pick An Emotion: ")
Adjective = input("Pick An Adjective: ")
Adverb = input("Pick A Adverb: ")
Food = input("Pick Your Favorite Food: ")

print("His",Item,"they weren't just",Color)
print("many",Color + "s","fading into one")
print("sometime they",Emotion)
print("sometime they ",Emotion2)
print("But they always had the",Adjective)
print("To",Adverb, "me that")
print("everything will be",Food)
